FIGS = ['figure' + str(num) + '.pdf' for num in range(1, 3)]
VALUES = ['number' + str(num) + '.txt' for num in range(1, 3)]

rule all:
    input:
        'paper.pdf'

rule make_paper:
    input:
        'paper.tex',
        'paper.bib',
        'requirements.out',
        FIGS,
        VALUES
    output:
        'paper.pdf'
    shell:
        """
        pdflatex paper.tex
        bibtex paper.aux
        pdflatex paper.tex
        pdflatex paper.tex
        """

rule plot_graphs:
    input:
        'analysis.py'
    output:
        FIGS,
        VALUES
    shell:
        """
        python analysis.py
        """

rule script_graphs:
    input:
        'analysis.ipynb',
        'requirements.out'
    output:
        'analysis.py'
    shell:
        'jupyter-nbconvert --to script analysis.ipynb'

rule install_packages:
    input:
        'requirements.txt'
    output:
        'requirements.out'
    shell:
        """
        pip install -r requirements.txt > requirements.out
        """
